### ISSUE TITLE
Differences in solidity block.number and web3.getBlockNumber

### ISSUE THREAD

**Issue by jgcogsystematictrading** [omgnetwork/optimism#291]
When I query block.number on the testnet chain in a solidity contract it returns a number above 9 million. Although the current post re-genesis block is ~5500, correctly returned by a function such as web3.eth.getBlockNumber(). This has been the case since the regenesis.

**Comment by CAPtheorem** [comment]
Looking now

**Comment by CAPtheorem** [comment]
1/ When you call `block.number` inside of a contract, you will get the `OVM block number`. This block number corresponds to the L1 block number of the last confirmed L1 ⇒ L2 transaction. Because L1 ⇒ L2 transactions are only considered confirmed after a certain number of blocks, this number will lag behind the current L1 block number by around five minutes. This was a deliberate design decision because many smart contracts rely on Ethereum's ~15s block time. If five minutes have passed since the last L1 ⇒ L2 transaction, the block number is automatically refreshed. So when you call block.number, you are executive values around 9 million.

2/ When you call `web3.eth.getBlockNumber()` with your rpc being the L2 - e.g. `https://rinkeby.omgx.network` or `https://mainnet.omgx.network`, you are getting the L2 block height, which for Rinkeby is currently around 5500.
