### ISSUE TITLE
Failed transaction

### ISSUE THREAD

**Issue by jowhhn01** [omgnetwork/optimism#551]
Bridging OMG to Boba failed transaction. Eth I used trying to make transaction is now gone

**Comment by CAPtheorem** [comment]
Could you provide more information about the transaction? Were you using the classic bridge or the fast bridge? Did the bridging fail before/after the approval or before/after the deposit? Note that when bridging OMG in particular, due to the 2017-era design of the OMG token, as many as three ETH-consuming steps may be needed to bridge OMG (Allowance set to zero, allowance set to bridge amount, bridge operation). The multistep allowance process was chosen in 2017 in an effort in increase the security of token transfers.

**Comment by CAPtheorem** [comment]
Update - both classical and fast L1->L2 bridges are operating normally. At current (Unix time: 16331455) gas prices (72 Gwei), the costs to bridge to L2 were measured to be:

```
**Classical Bridge** 0.0032 ETH for approval, 0.0371 ETH to bridge = 0.0403 ETH total cost
**Fast Bridge**      0.0025 ETH for approval, 0.0131 ETH to bridge = 0.0156 ETH total cost
```

Generally the *Fast Bridge* is about 1/2 the price of the classical deposit, despite the 0.1% fast swap fee which is paid out to the liquidity providers.
